name: Workflow
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Should this run deploy image"
        required: false
        default: 'false'
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set environment
      run: |
        IS_DEPLOY=$( \
          [[ \
            ( \
              '${{ github.event_name }}' == 'push'
            ) || \
            ( \
             '${{ github.event_name }}' == 'workflow_dispatch' && \
             '${{ github.event.inputs.deploy }}' == 'true' \
            ) \
          ]] && echo true || echo false
        )
        echo "IS_DEPLOY=$IS_DEPLOY" >> $GITHUB_ENV
    - name: "[DEPLOY] Tag commit"
      if: env.IS_DEPLOY == 'true'
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        tag: "remove_this_tag"

